format_version: 10

pipelines:

  python-pipeline:
    group: defaultGroup

    materials:
      mygit:
        git: https://github.com/Rahul-3043/Go_Cd_Pipeline.git
        branch: main

    stages:

      - build:
          jobs:
            python-build-job:
              resources:
                - python
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        echo "===== BUILD STAGE ====="
                        python --version
                        echo "print('Hello from Python Agent')" > app.py

      - test:
          jobs:
            python-test-job:
              resources:
                - python
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        echo "===== TEST STAGE ====="
                        python app.py
                        echo "Test Successful"
